export const colorsData = [
  { id: 9, color: 'bbf2da', name: 'Decentně zelená' },
  { id: 10, color: 'f5eaa2', name: 'Decentně žlutá' },
  { id: 11, color: 'fadfc8', name: 'Decentně oranžová' },
  { id: 12, color: 'fcd6d2', name: 'Decentně červená' },
  { id: 13, color: 'e1d7fc', name: 'Decentně fialová' },
  { id: 14, color: '4ecf97', name: 'Zelená' },
  { id: 15, color: 'f0d24f', name: 'Žlutá' },
  { id: 16, color: 'faa966', name: 'Oranžová' },
  { id: 17, color: 'f2766b', name: 'Červená' },
  { id: 18, color: 'a68aed', name: 'Fialová' },
  { id: 19, color: '24855c', name: 'Výrazně zelená' },
  { id: 20, color: '8f710e', name: 'Výrazně žlutá' },
  { id: 21, color: 'bd560d', name: 'Výrazně oranžová' },
  { id: 22, color: 'c43e2f', name: 'Výrazně červená' },
  { id: 23, color: '7654c4', name: 'Výrazně fialová' },
  { id: 24, color: 'd1dfff', name: 'Decentně modrá' },
  { id: 25, color: 'c8ebfa', name: 'Decentně mořská' },
  { id: 26, color: 'd0f2aa', name: 'Decentně limetková' },
  { id: 27, color: 'fcd2ed', name: 'Decentně růžová' },
  { id: 28, color: 'dadde3', name: 'Decetně šedá' },
  { id: 29, color: '6d95fc', name: 'Modrá' },
  { id: 30, color: '76bfde', name: 'Mořská' },
  { id: 31, color: '90c94f', name: 'Limetková' },
  { id: 32, color: 'e673ba', name: 'Růžová' },
  { id: 33, color: '8790a3', name: 'Šedá' },
  { id: 34, color: '4058e3', name: 'Výrazně modrá' },
  { id: 35, color: '327999', name: 'Výrazně nebeská' },
  { id: 36, color: '59822a', name: 'Výrazně limetková' },
  { id: 37, color: 'ad4586', name: 'Výrazně růžová' },
  { id: 38, color: '656e85', name: 'Výrazně šedá' }
];